### ISSUE TITLE
Spending money on GitHub actions: what would be the scale?

### ISSUE THREAD

**Issue by ryjones** [PQCA/TAC#20]
### Please share any additional details on this topic

[OQS](https://github.com/open-quantum-safe/liboqs/issues/1789) has requested the ability to run ARM builds on GitHub. The first step of this is having a budget estimated so it can be requested; the second step is to get the orgs into the ARM runner beta.

### Detail what actions or feedback you would like from the TAC

An estimated spend and decision on how broadly this should be used. I don't know how much, if anything, is spent at CircleCI, for comparison.

### How much time do you need for this topic?

5 minutes or less

**Comment by baentsch** [comment]
FWIW, input [here](https://github.com/orgs/open-quantum-safe/discussions/1792#discussioncomment-9429995).

Please consider in your budgeting exercise that the project should be able to grow and more contributions & support for more platforms means more PRs, means more CI resources.

For OQS our goal has been to stay "lean and mean"/[ecologically responsible](https://github.com/open-quantum-safe/tsc/issues/5) (e.g., to test some platforms only in downstream sub projects as opposed to every sub project or do do weekly tests instead of "merge-at-main" CI, etc.) -- but this required work and discipline that someone needs to provide also going forward.

**Comment by ryjones** [comment]
> Please consider in your budgeting exercise that the project should be able to grow and more contributions & support for more platforms means more PRs, means more CI resources.

Yup. My hope is that with the exception of ARM runners, we are able to keep PQCA on the free plan at GitHub.

**Comment by planetf1** [comment]
Within PQCP we have some requirements from the arm implementations to use AWS. I don't believe github arm runners meet their requirements.

More details at https://github.com/pq-code-package/mlkem-c-aarch64/issues/34

**Comment by Naomi-Wash** [comment]
This has been approved by the governing board.
